language: python

python:
  - "2.7"

install:
  - pip install --upgrade setuptools
  - pip install -e .
  - pip install -e ".[test]"
  - pip install coveralls

script:
  - py.test --cov=baggins

after_success:
  - coveralls
