#!/usr/bin/env python


import argparse


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Generate bagit bags from LSDI digitized book content')
    parser.add_argument('item_ids', metavar='ID', nargs='*',
                        help='Digitization Workflow Item ID')
    options = parser.parse_args()
    if not options.item_ids:
        print 'Please specify one or more item ids for items to process'
        parser.print_help()
        exit()

